name: ZIP Sectors

on:
  push:
    branches:
      - main
      
permissions: write-all
      
jobs:
    Archive:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: montudor/action-zip@v1
          with:
            args: zip -qq -r ALL_SECTORS.zip . -i *.isc Include
            # testing
        - run: ls -la
        - run: export title="Automatic Release $(date -u +%F_%H:%M:%S)"
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: false
            title: "${{ env.title }}"
            files: |
              *.zip
