name: ZIP Sectors

on:
  push:
    branches:
      - main
      
permissions: write-all
      
jobs:
    Archive:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: montudor/action-zip@v1
          with:
            args: zip -qq -r CZEG.zip . -i Include/CA/CZEG/* "CZEG.isc"
        - uses: montudor/action-zip@v1
          with:
            args: zip -qq -r CZQM.zip . -i Include/CA/CZQM/* "CZQM.isc"
        - uses: montudor/action-zip@v1
          with:
            args: zip -qq -r CZUL.zip . -i Include/CA/CZUL/* "CZUL.isc"
        - uses: montudor/action-zip@v1
          with:
            args: zip -qq -r CZQX.zip . -i Include/CA/CZQX/* "CZQX.isc"              
        - uses: montudor/action-zip@v1
          with:
            args: zip -qq -r CZVR.zip . -i Include/CA/CZVR/* "CZVR.isc"
        - uses: montudor/action-zip@v1
          with:
            args: zip -qq -r CZWG.zip . -i Include/CA/CZWG/* "CZWG.isc"
        - uses: montudor/action-zip@v1
          with:
            args: zip -qq -r CZYZ.zip . -i Include/CA/CZYZ/* "CZYZ.isc"
        - uses: montudor/action-zip@v1
          with:
            args: zip -qq -r ALL_SECTORS.zip . -i *.zip
            # testing
        - run: ls -la
        - run: export title="Automatic Release $(date -u +%F_%H:%M:%S)"
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: false
            title: "${{ env.title }}"
            files: |
              *.zip
